In [1]:
# 1. Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.
    # Tek boyutlu arraylere vektor, cok boyutlu arraylere matris denir.

In [2]:
# 2. 10 elemanli bir listeden NumPy Array’i olusturunuz.
import numpy as np
my_list = [i for i in range(10)]
array1 = np.array(my_list)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 3. Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.
zeros = np.zeros((10,10), dtype='int32')
zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
# 4. Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
ones = np.ones((10,10))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
# 5. Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.
nines = np.full((10,10),9, dtype = 'int32')
nines

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [6]:
# 6. 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.
array2 = np.arange(5,25,3)
array2

array([ 5,  8, 11, 14, 17, 20, 23])

In [7]:
# 7. -1 ile 1 arasinda 30 adet Array olusturunuz.
array3 = np.linspace(-1,1,30)
array3

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [8]:
# 8. 0 ile 30 arasinda 5x6’lik bir matris olusturun.
array4 = np.random.randint(0,30,(5,6))
array4

array([[ 5, 12,  7,  4, 19, 25],
       [ 6,  5,  2, 10,  5, 28],
       [22,  9,  3, 26,  3, 20],
       [18,  3, 16, 21,  2, 21],
       [ 5,  7, 17,  1, 21, 12]])

In [9]:
# 9. Kosegenleri 1 olan 10x10’luk bir matris olusturunuz. 
array5 = np.eye(10)
array5

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
# 10. 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
#     10.1 eleman sayisini
#     10.2 boyut bilgisini/sayisini
#     10.3 satir X sutun bilgisini
#     10.4 veri tipini numpy metodlariyla yazdiriniz.
array5 = np.random.randint(0,10,(5,10))
print(array5)
print("eleman sayisi = ", array5.size)
print("boyut bilgisi = ", array5.ndim)
print("satir,sutun bilgisi = ", array5.shape)
print("veri tipi = ", array5.dtype)

[[9 8 5 1 9 7 2 0 4 3]
 [6 7 6 5 3 1 6 7 1 2]
 [6 2 6 0 9 5 4 2 3 6]
 [6 4 9 0 1 0 6 7 8 5]
 [0 1 6 8 3 1 3 2 7 3]]
eleman sayisi =  50
boyut bilgisi =  2
satir,sutun bilgisi =  (5, 10)
veri tipi =  int32


In [11]:
# 11. 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz (3 boyutlu bir matris olusturulacak).
array6 = np.random.randint(0,10,(3,4,7))
array6

array([[[5, 1, 6, 7, 0, 8, 7],
        [3, 5, 6, 7, 9, 3, 0],
        [0, 1, 7, 7, 2, 6, 4],
        [0, 3, 6, 4, 4, 7, 2]],

       [[7, 8, 3, 9, 6, 0, 6],
        [5, 0, 2, 0, 7, 1, 7],
        [1, 7, 9, 6, 4, 4, 4],
        [5, 1, 3, 7, 8, 9, 8]],

       [[7, 4, 8, 3, 2, 3, 9],
        [4, 6, 5, 5, 1, 3, 3],
        [2, 7, 4, 3, 1, 9, 2],
        [0, 9, 5, 3, 7, 0, 0]]])

In [12]:
# 12. Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz.
array7 = np.arange(12)
matris1 = array7.reshape(3,4)
matris1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
# 13. 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.
array8 = np.arange(5)
array9 = np.arange(5,10)
array10 = np.arange(10,15)
array11 = np.arange(15,20)
array_con = np.concatenate([array8,array9,array10,array11])
array_con

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
# 14. 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz.
vector1 = np.random.randint(0,9,(2,4))
matris2 = np.random.randint(10,18,(2,4))
matris_con = np.concatenate([vector1,matris2], axis=1)
matris_con

array([[ 6,  6,  8,  8, 14, 16, 17, 12],
       [ 8,  8,  3,  2, 12, 17, 17, 17]])

In [15]:
#15. Numpy’da “axis=1” ve “axis=0”  arasinda ne fark vardir. Teorik olarak yaziniz?
    # 'axis=1' satirlari, 'axis=0' sutunlari belirtmek icin kullanilir. 
    # Orn. concatenate metodunda, iki matrisi horizontal olarak birlestirmek icin axis=1, 
    # vertical olarak birlestirmek icin axis=0 kodunu yazariz.
    # numpy'de default deger axis=0'dir.

In [16]:
# 16. Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.
# Horizontal birlestirme
matris3 = np.random.randint(0,6,(2,3))
matris4 = np.random.randint(10,18,(2,4))
matris_hstack = np.hstack([matris3,matris4])
matris_hstack

array([[ 1,  1,  2, 11, 13, 16, 12],
       [ 4,  5,  0, 15, 17, 17, 13]])

In [17]:
# Vertical birlestirme
matris5 = np.random.randint(0,6,(3,2))
matris6 = np.random.randint(10,18,(4,2))
matris_vstack = np.vstack([matris5,matris6])
matris_vstack

array([[ 3,  5],
       [ 3,  3],
       [ 2,  4],
       [13, 12],
       [14, 14],
       [15, 11],
       [12, 12]])

In [18]:
# 17. 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.
my_list2 = [i for i in range(11,21)]
a1,a2,a3,a4 = np.split(my_list,(2,5,8))
print(a1,a2,a3,a4)

[0 1] [2 3 4] [5 6 7] [8 9]


In [48]:
# 18. Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.
# Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.
array12 = np.random.randint(40, size = (12))
array12_sorted = np.sort(array12)
print(array12_sorted)
for i in list(array12_sorted):
        print(f"number: {i} , index: {list(array12_sorted).index(i)}")

[ 0  4  9 17 18 22 22 22 28 31 36 36]
number: 0 , index: 0
number: 4 , index: 1
number: 9 , index: 2
number: 17 , index: 3
number: 18 , index: 4
number: 22 , index: 5
number: 22 , index: 5
number: 22 , index: 5
number: 28 , index: 8
number: 31 , index: 9
number: 36 , index: 10
number: 36 , index: 10


In [20]:
# 19. 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.
vector2 = np.random.randint(20,100, size=(20))
print(f"vector 2= {vector2}\n3rd: {vector2[2]}\n5th: {vector2[4]}\n7th: {vector2[6]}")

vector 2= [38 92 37 23 91 65 59 96 60 28 68 83 66 69 49 88 64 55 23 86]
3rd: 37
5th: 91
7th: 59


In [21]:
# 20. 10 elemanli random bir vektor olusturunuz ve bu arrayin  4. elemanini farkli bir sayiyla degistiriniz.
vector3 = np.random.randint(20,100, size=(10))
print(vector3)
vector3[3]=1111
print(vector3)

[44 43 80 86 84 49 81 33 20 40]
[  44   43   80 1111   84   49   81   33   20   40]


In [22]:
# 21. “Diagonal Matrix” ve “Trace Matrix”  kavramlari hakkinda kucuk bir arastirma yapip, bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.
    # Diagonal Matrix: Kosegenleri sol yukaridan sag asagiya dogru 1 olan matrislerdir.
        # Ayrica diagonal matrisin satir ve sutun sayilari birbirine esittir(kare matris). 
    # Trace Matrix: Kare bir matriste sol yukardan sag asagiya kosegenlerin toplamidir. 

In [23]:
# 22. 5x5’lik Diagonal bir matris olusturunuz ve 
# Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)
matris8 = np.eye(5,5)
for i in range(5):
    for j in range(5):
        if i==j:
            print(matris8[i,j])

1.0
1.0
1.0
1.0
1.0


In [24]:
# 23. 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.
vector4 = np.arange(10,20)
vector4[3:]

array([13, 14, 15, 16, 17, 18, 19])

In [25]:
# 24. 10X10 luk bir matris olusturunuz
matris7 = np.random.randint(100, size = (10,10))
matris7

array([[36, 25, 92, 61, 55, 34,  3, 22, 27, 72],
       [77, 94, 82, 45, 72, 48, 58, 26, 74, 80],
       [11, 30, 82, 55, 69,  3, 19, 28,  6, 61],
       [33, 66, 77, 50, 41, 40, 45, 29, 48, 97],
       [98,  4, 83, 69, 39, 89, 94, 56, 25, 17],
       [14, 60,  1, 72, 88, 12, 74, 75, 94, 85],
       [30, 24, 43, 35, 51, 93, 52, 74, 30, 55],
       [57, 80, 93, 15, 39, 22, 22, 83, 50, 97],
       [ 5, 35, 60, 95, 67,  2, 35, 28, 16, 31],
       [75, 91, 11, 35, 55, 86, 85, 55, 62, 34]])

In [26]:
# 24.1 3.satir ve 5.sutuna ulasiniz.
matris7[2,4]

69

In [27]:
# 24.2 5.sutunun tum satirlarina ulasiniz.
matris7[:,4]

array([55, 72, 69, 41, 39, 88, 51, 39, 67, 55])

In [28]:
# 24.3 Tum sutunlarin 2.satirlarina ulasiniz.
matris7[1,:]

array([77, 94, 82, 45, 72, 48, 58, 26, 74, 80])

In [29]:
# 24.4 tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
matris7[1:8,:]

array([[77, 94, 82, 45, 72, 48, 58, 26, 74, 80],
       [11, 30, 82, 55, 69,  3, 19, 28,  6, 61],
       [33, 66, 77, 50, 41, 40, 45, 29, 48, 97],
       [98,  4, 83, 69, 39, 89, 94, 56, 25, 17],
       [14, 60,  1, 72, 88, 12, 74, 75, 94, 85],
       [30, 24, 43, 35, 51, 93, 52, 74, 30, 55],
       [57, 80, 93, 15, 39, 22, 22, 83, 50, 97]])

In [30]:
# 24.5. satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
matris7[2:5,3:7]

array([[55, 69,  3, 19],
       [50, 41, 40, 45],
       [69, 39, 89, 94]])

In [31]:
# 24.6 satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
matris7[5:,:4]

array([[14, 60,  1, 72],
       [30, 24, 43, 35],
       [57, 80, 93, 15],
       [ 5, 35, 60, 95],
       [75, 91, 11, 35]])

In [32]:
# 24.7 sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
matris7[:,[3,6,9]]

array([[61,  3, 72],
       [45, 58, 80],
       [55, 19, 61],
       [50, 45, 97],
       [69, 94, 17],
       [72, 74, 85],
       [35, 52, 55],
       [15, 22, 97],
       [95, 35, 31],
       [35, 85, 34]])

In [33]:
# 24.8 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz. 
matris7[5,5]=1979
matris7

array([[  36,   25,   92,   61,   55,   34,    3,   22,   27,   72],
       [  77,   94,   82,   45,   72,   48,   58,   26,   74,   80],
       [  11,   30,   82,   55,   69,    3,   19,   28,    6,   61],
       [  33,   66,   77,   50,   41,   40,   45,   29,   48,   97],
       [  98,    4,   83,   69,   39,   89,   94,   56,   25,   17],
       [  14,   60,    1,   72,   88, 1979,   74,   75,   94,   85],
       [  30,   24,   43,   35,   51,   93,   52,   74,   30,   55],
       [  57,   80,   93,   15,   39,   22,   22,   83,   50,   97],
       [   5,   35,   60,   95,   67,    2,   35,   28,   16,   31],
       [  75,   91,   11,   35,   55,   86,   85,   55,   62,   34]])

In [34]:
# 25. 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
array13 = np.arange(0,50,5)
array13

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [35]:
# 25.1 20 den buyuk olan kac deger var.
np.sum(array13>20)

5

In [36]:
# 25.2 30'dan kucuk kac deger var
np.sum(array13<30)

6

In [37]:
# 25.3 icerisinde 33 gecen kac deger var
np.sum(array13==33)

0

In [38]:
# 25.4 olusturulan arrayin tum elemanlarini 5 ile carpin.
np.multiply(array13,5)

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [39]:
# 25.5 olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.
array13%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [40]:
# 26. 0 ile 1 arasinda 50 elamanli bir array olusturunuz 
array14 = np.random.normal(0,1,50)
array14

array([-0.26258331,  0.48312463,  0.56933806, -1.21010528,  0.3468017 ,
        1.27257198, -1.9444687 , -0.32605668, -0.89418093,  0.2887614 ,
       -1.85045733, -0.86585015, -0.451081  , -1.05492811, -0.96396377,
        0.64029151, -0.51259743,  0.88597221, -0.56741524, -0.05792658,
        0.8995761 , -1.8134648 , -0.06314305,  1.25833623, -0.67416216,
        0.57177182,  0.31522564,  0.80539273, -0.20660309, -1.92777645,
        1.34796442,  1.53030648,  0.60617021,  0.59579336, -0.18454676,
        0.08843456, -1.21091131,  0.59235875,  0.97993673, -0.0861714 ,
       -0.67237885,  0.73377289,  2.51010511, -1.65502053, -0.92686784,
       -0.27886282, -0.54924087,  0.61174881,  0.92052521, -0.54420729])

In [41]:
#26.1 ortalamasini aliniz.
np.mean(array14)

-0.05801382306236492

In [42]:
# 26.2 standart sapmasini aliniz.
np.std(array14)

0.9808490721349055

In [43]:
# 26.3 varyansini aliniz.
np.var(array14)

0.9620649023079051

In [44]:
# 26.4 median’ini aliniz.
np.median(array14)

-0.07465722532543795

In [45]:
# 26.5 en kucuk degeri bulunuz.
np.min(array14)

-1.9444686952752575

In [46]:
# 26.6 en buyuk degeri bulunuz.
np.max(array14)

2.510105107133254