In [1]:
# 1. Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.
    # Tek boyutlu arraylere vektor, cok boyutlu arraylere matris denir.

In [2]:
# 2. 10 elemanli bir listeden NumPy Array’i olusturunuz.
import numpy as np
my_list = [i for i in range(10)]
array1 = np.array(my_list)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 3. Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.
zeros = np.zeros((10,10), dtype='int32')
zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
# 4. Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
ones = np.ones((10,10))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
# 5. Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.
nines = np.full((10,10),9, dtype = 'int32')
nines

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [6]:
# 6. 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.
array2 = np.arange(5,25,3)
array2

array([ 5,  8, 11, 14, 17, 20, 23])

In [7]:
# 7. -1 ile 1 arasinda 30 adet Array olusturunuz.
array3 = np.linspace(-1,1,30)
array3

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [47]:
# 8. 0 ile 30 arasinda 5x6’lik bir matris olusturun.
array4 = np.random.randint(0,30,(5,6))
array4

array([[ 4, 16,  6,  3,  6, 19],
       [ 6,  1,  8,  0, 22, 23],
       [26,  7, 29, 24,  7, 24],
       [ 2, 25, 15, 23, 21,  1],
       [ 1,  9, 27,  2,  9, 18]])

In [9]:
# 9. Kosegenleri 1 olan 10x10’luk bir matris olusturunuz. 
array5 = np.eye(10)
array5

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [48]:
# 10. 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
#     10.1 eleman sayisini
#     10.2 boyut bilgisini/sayisini
#     10.3 satir X sutun bilgisini
#     10.4 veri tipini numpy metodlariyla yazdiriniz.
array5 = np.random.randint(0,10,(5,10))
print(array5)
print("eleman sayisi = ", array5.size)
print("boyut bilgisi = ", array5.ndim)
print("satir,sutun bilgisi = ", array5.shape)
print("veri tipi = ", array5.dtype)

[[3 1 9 4 8 8 6 0 6 8]
 [3 8 7 7 7 0 8 5 3 2]
 [3 2 1 6 9 7 4 5 1 0]
 [1 1 5 1 5 2 9 1 0 9]
 [0 3 4 5 0 5 9 0 6 4]]
eleman sayisi =  50
boyut bilgisi =  2
satir,sutun bilgisi =  (5, 10)
veri tipi =  int32


In [11]:
# 11. 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz (3 boyutlu bir matris olusturulacak).
array6 = np.random.randint(0,10,(3,4,7))
array6

array([[[3, 6, 0, 1, 9, 3, 4],
        [1, 2, 4, 5, 9, 2, 5],
        [6, 7, 0, 5, 4, 5, 9],
        [2, 0, 4, 7, 3, 8, 5]],

       [[7, 0, 3, 8, 9, 5, 9],
        [9, 7, 0, 1, 1, 5, 0],
        [5, 6, 1, 6, 8, 7, 5],
        [8, 9, 3, 3, 0, 0, 0]],

       [[6, 0, 1, 7, 9, 7, 2],
        [4, 9, 7, 7, 6, 0, 7],
        [9, 0, 0, 6, 0, 1, 7],
        [6, 5, 3, 7, 4, 7, 7]]])

In [12]:
# 12. Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz.
array7 = np.arange(12)
matris1 = array7.reshape(3,4)
matris1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
# 13. 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.
array8 = np.arange(5)
array9 = np.arange(5,10)
array10 = np.arange(10,15)
array11 = np.arange(15,20)
array_con = np.concatenate([array8,array9,array10,array11])
array_con

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
# 14. 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz.
vector1 = np.random.randint(0,9,(1,4))
matris2 = np.random.randint(10,18,(2,4))
matris_con = np.concatenate([vector1,matris2])
matris_con

array([[ 7,  5,  7,  6],
       [14, 14, 15, 11],
       [11, 16, 16, 10]])

In [15]:
#15. Numpy’da “axis=1” ve “axis=0”  arasinda ne fark vardir. Teorik olarak yaziniz?
    # 'axis=1' satirlar, 'axis=0' sutunlari belirtmek icin kullanilir. 
    # Orn. concatenate metodunda, iki matrisi horizontal olarak birlestirmek icin axis=1, 
    # vertical olarak birlestirmek icin axis=0 kodunu yazariz.
    # numpy'de default deger axis=0'dir.

In [16]:
# 16. Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.
# Horizontal birlestirme
matris3 = np.random.randint(0,6,(2,3))
matris4 = np.random.randint(10,18,(2,4))
matris_hstack = np.hstack([matris3,matris4])
matris_hstack

array([[ 5,  5,  0, 11, 13, 16, 11],
       [ 0,  4,  4, 16, 10, 17, 17]])

In [17]:
# Vertical birlestirme
matris5 = np.random.randint(0,6,(3,2))
matris6 = np.random.randint(10,18,(4,2))
matris_vstack = np.vstack([matris5,matris6])
matris_vstack

array([[ 0,  3],
       [ 5,  5],
       [ 3,  2],
       [16, 10],
       [17, 13],
       [17, 10],
       [11, 16]])

In [18]:
# 17. 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.
my_list2 = [i for i in range(11,21)]
a1,a2,a3,a4 = np.split(my_list,(2,5,8))
print(a1,a2,a3,a4)

[0 1] [2 3 4] [5 6 7] [8 9]


In [19]:
# 18. Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.
# Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.
array12 = np.random.randint(40, size = (12))
array12_sorted = np.sort(array12)
array12_sorted
for i in list(array12_sorted):
        print(f"number: {i} , index: {list(array12_sorted).index(i)}")

number: 0 , index: 0
number: 12 , index: 1
number: 17 , index: 2
number: 20 , index: 3
number: 21 , index: 4
number: 24 , index: 5
number: 25 , index: 6
number: 25 , index: 6
number: 26 , index: 8
number: 28 , index: 9
number: 29 , index: 10
number: 36 , index: 11


In [54]:
# 19. 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.
vector2 = np.random.randint(20,100, size=(20))
print(f"vector 2= {vector2}\n3rd: {vector2[2]}\n5th: {vector2[4]}\n7th: {vector2[6]}")

vector 2= [68 29 59 85 58 74 46 34 95 37 29 46 41 54 72 64 98 88 25 95]
3rd: 59
5th: 58
7th: 46


In [21]:
# 20. 10 elemanli random bir vektor olusturunuz ve bu arrayin  4. elemanini farkli bir sayiyla degistiriniz.
vector3 = np.random.randint(20,100, size=(10))
print(vector3)
vector3[3]=1111
print(vector3)

[47 93 70 61 49 34 94 70 56 57]
[  47   93   70 1111   49   34   94   70   56   57]


In [22]:
# 21. “Diagonal Matrix” ve “Trace Matrix”  kavramlari hakkinda kucuk bir arastirma yapip, bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.
    # Diagonal Matrix: Kosegenleri sol yukaridan sag asagiya dogru 1 olan matrislerdir.
        # Ayrica diagonal matrisin satir ve sutun sayilari birbirine esittir(kare matris). 
    # Trace Matrix: Kare bir matriste sol yukardan sag asagiya kosegenlerin toplamidir. 

In [65]:
# 22. 5x5’lik Diagonal bir matris olusturunuz ve 
# Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)
matris8 = np.eye(5,5)
for i in range(5):
    for j in range(5):
        if i==j:
            print(matris8[i,j])

1.0
1.0
1.0
1.0
1.0


In [24]:
# 23. 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.
vector4 = np.arange(10,20)
vector4[3:]

array([13, 14, 15, 16, 17, 18, 19])

In [25]:
# 24. 10X10 luk bir matris olusturunuz
matris7 = np.random.randint(100, size = (10,10))
matris7

array([[71, 23, 52, 48, 75,  3, 10, 19,  9, 27],
       [98, 65, 63,  8, 74, 45, 45, 27, 25, 48],
       [23, 78, 77, 60, 77, 36, 78, 44, 91, 36],
       [87,  1, 21, 55, 24, 52, 48, 17, 53, 41],
       [84, 76, 19,  1, 23, 92, 27, 80, 16, 28],
       [73, 40, 63, 74, 38, 78, 18, 90,  9, 67],
       [33, 39,  8, 13, 34, 75, 60, 11, 45, 32],
       [77, 34, 24,  0, 17, 79,  5, 63, 36, 77],
       [93, 86,  7, 28, 40,  9, 50,  2, 59, 15],
       [64, 54, 99, 21, 40, 26, 28, 49, 32, 54]])

In [26]:
# 24.1 3.satir ve 5.sutuna ulasiniz.
matris7[2,4]

77

In [27]:
# 24.2 5.sutunun tum satirlarina ulasiniz.
matris7[:,4]

array([75, 74, 77, 24, 23, 38, 34, 17, 40, 40])

In [28]:
# 24.3 Tum sutunlarin 2.satirlarina ulasiniz.
matris7[1,:]

array([98, 65, 63,  8, 74, 45, 45, 27, 25, 48])

In [29]:
# 24.4 tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
matris7[1:8,:]

array([[98, 65, 63,  8, 74, 45, 45, 27, 25, 48],
       [23, 78, 77, 60, 77, 36, 78, 44, 91, 36],
       [87,  1, 21, 55, 24, 52, 48, 17, 53, 41],
       [84, 76, 19,  1, 23, 92, 27, 80, 16, 28],
       [73, 40, 63, 74, 38, 78, 18, 90,  9, 67],
       [33, 39,  8, 13, 34, 75, 60, 11, 45, 32],
       [77, 34, 24,  0, 17, 79,  5, 63, 36, 77]])

In [30]:
# 24.5. satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
matris7[2:5,3:7]

array([[60, 77, 36, 78],
       [55, 24, 52, 48],
       [ 1, 23, 92, 27]])

In [31]:
# 24.6 satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
matris7[5:,:4]

array([[73, 40, 63, 74],
       [33, 39,  8, 13],
       [77, 34, 24,  0],
       [93, 86,  7, 28],
       [64, 54, 99, 21]])

In [32]:
# 24.7 sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
matris7[:,[3,6,9]]

array([[48, 10, 27],
       [ 8, 45, 48],
       [60, 78, 36],
       [55, 48, 41],
       [ 1, 27, 28],
       [74, 18, 67],
       [13, 60, 32],
       [ 0,  5, 77],
       [28, 50, 15],
       [21, 28, 54]])

In [33]:
# 24.8 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz. 
matris7[5,5]=1979
matris7

array([[  71,   23,   52,   48,   75,    3,   10,   19,    9,   27],
       [  98,   65,   63,    8,   74,   45,   45,   27,   25,   48],
       [  23,   78,   77,   60,   77,   36,   78,   44,   91,   36],
       [  87,    1,   21,   55,   24,   52,   48,   17,   53,   41],
       [  84,   76,   19,    1,   23,   92,   27,   80,   16,   28],
       [  73,   40,   63,   74,   38, 1979,   18,   90,    9,   67],
       [  33,   39,    8,   13,   34,   75,   60,   11,   45,   32],
       [  77,   34,   24,    0,   17,   79,    5,   63,   36,   77],
       [  93,   86,    7,   28,   40,    9,   50,    2,   59,   15],
       [  64,   54,   99,   21,   40,   26,   28,   49,   32,   54]])

In [34]:
# 25. 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
array13 = np.arange(0,50,5)
array13

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [35]:
# 25.1 20 den buyuk olan kac deger var.
np.sum(array13>20)

5

In [36]:
# 25.2 30'dan kucuk kac deger var
np.sum(array13<30)

6

In [37]:
# 25.3 icerisinde 33 gecen kac deger var
np.sum(array13==33)

0

In [38]:
# 25.4 olusturulan arrayin tum elemanlarini 5 ile carpin.
np.multiply(array13,5)

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [39]:
# 25.5 olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.
array13%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [40]:
# 26. 0 ile 1 arasinda 50 elamanli bir array olusturunuz 
array14 = np.random.normal(0,1,50)
array14

array([ 0.14266141,  0.47674441,  1.1661217 ,  2.2532709 ,  0.18735   ,
        0.52083733, -0.48500071, -1.02972721, -0.80855895, -1.23869844,
        0.40768313,  1.05208614,  1.22405587,  0.47774465,  1.42031636,
       -2.76557672,  0.39029355, -1.06935744, -0.99092279,  1.72460524,
        1.23614735, -0.02203865,  1.47544882,  1.32002354,  0.33790943,
        0.50969165, -0.38159649,  1.70499522,  1.11171224, -1.17347399,
       -1.42370849, -1.75253474,  0.6101572 ,  1.0469982 , -0.27018191,
        0.83360802, -2.64474467, -0.61620172,  0.09493824,  0.28785449,
       -0.61819664, -0.80754527,  2.3300982 , -0.82440394,  1.73393823,
        0.94875913,  0.03975237, -1.07669861, -0.61602424,  2.19337109])

In [41]:
#26.1 ortalamasini aliniz.
np.mean(array14)

0.17287965059993401

In [42]:
# 26.2 standart sapmasini aliniz.
np.std(array14)

1.1881707894377191

In [43]:
# 26.3 varyansini aliniz.
np.var(array14)

1.411749824873053

In [44]:
# 26.4 median’ini aliniz.
np.median(array14)

0.31288195923654794

In [45]:
# 26.5 en kucuk degeri bulunuz.
np.min(array14)

-2.7655767196635104

In [46]:
# 26.6 en buyuk degeri bulunuz.
np.max(array14)

2.330098201666112